apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: dla-lm-1a-dtg
  annotations:
    flux.weave.works/automated: "false"
  namespace: dla-lm-1a-ns
spec:
  releaseName: dla-lm-1a-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: git@github.com:Singh-Jas/blockchain-automation-framework.git
    ref: dev-indy-release
  values:
    metadata:
      name: dla-lm-1a-dtg
      namespace: dla-lm-1a-ns
    organization:
      name: dla-lm-1a
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"tq-trustee","dest":"Du9rmXahMWUdPr7AhbCCEM","role":"0","verkey":"82mang9srzzxbfLu2KKNMGFsz1kGMynZEnwdnFbrbuvS"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"steward-1","dest":"H7iJ6ebjdcWyH8qeSeLTNc","role":"2","verkey":"9nT68AEsZWfc8BuH4hUFbav9aNx7F8Gt7PDmXqrHE5N3"},"metadata":{"from":"Du9rmXahMWUdPr7AhbCCEM"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"steward-2","dest":"U1QrUBNf2Wty6ad1c7U1J5","role":"2","verkey":"FikMB84GqdBHHctLpe6wRa29f6WMyWET7ZDWQAA5AaKd"},"metadata":{"from":"Du9rmXahMWUdPr7AhbCCEM"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"steward-3","dest":"Cq9Kei1TmPHVR9MbVq8xg8","role":"2","verkey":"7SyMBLdoz9jsqBbJxXqvsFXM3tzr5kTzPbBtqat1CQ65"},"metadata":{"from":"Du9rmXahMWUdPr7AhbCCEM"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"steward-4","dest":"51xG8uK7UMqF7TdsLYEfMr","role":"2","verkey":"3By6bX9it6nYUnwnXQgW5X4pu7cqjoeXkRzzVCQzvN3a"},"metadata":{"from":"Du9rmXahMWUdPr7AhbCCEM"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
