apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: baf-dzamba-partner-partner-steward-1-auth-job
  annotations:
    flux.weave.works/automated: "false"
  namespace: baf-dzamba-partner-ns
spec:
  releaseName: baf-dzamba-partner-partner-steward-1-auth-job
  chart:
    path: platforms/hyperledger-indy/charts/indy-auth-job
    git: git@github.com:Singh-Jas/blockchain-automation-framework.git
    ref: test-indy-release
  values:
    metadata:
      name: baf-dzamba-partner-partner-steward-1-auth-job
      namespace: baf-dzamba-partner-ns
    network:
      name: baf
      kubernetes_url: https://192.168.99.103:8443
    image:
      name: baf-dzamba-partner
      repository: alpine:3.9.4
    vault:
      address: http://192.168.1.155:8200
      keyPath: baf-dzamba-partner.stewards
      identity: partner-steward-1
      admin_auth_path: kubernetes-baf-dzamba-partner-admin-auth
      policy: baf-dzamba-partner-partner-steward-1-ro
      policy_content: path \"/baf-dzamba-partner/stewards/partner-steward-1/*\" { capabilities = [ \"read\", \"list\" ] }
      auth_path: kubernetes-baf-dzamba-partner-partner-steward-1-auth
    account:
      admin_service: baf-dzamba-partner-admin-vault-auth
      admin_role: rw
      service: baf-dzamba-partner-partner-steward-1-vault-auth
      role: ro
