apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: baf-dzamba-partner-dtg
  annotations:
    flux.weave.works/automated: "false"
  namespace: baf-dzamba-partner-ns
spec:
  releaseName: baf-dzamba-partner-dtg
  chart:
    path: platforms/hyperledger-indy/charts/indy-domain-genesis
    git: ssh://git@github.com/Singh-Jas/blockchain-automation-framework.git
    ref: test-indy-release
  values:
    metadata:
      name: baf-dzamba-partner-dtg
      namespace: baf-dzamba-partner-ns
    organization:
      name: baf-dzamba-partner
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"FKCQJg2EMprKRvXx7dxGPn","role":"0","verkey":"8oV9jhD8UtJHvbn9DwP5yVvrNXhVQGCn6rrbHSFYFe1p"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-1","dest":"5S6ynyR9poDzGaejEZirhJ","role":"2","verkey":"3R8Y4SMSVgjj8SFbusGpYWBKd1QAJxY2A7vY66fp5Hdq"},"metadata":{"from":"FKCQJg2EMprKRvXx7dxGPn"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"provider-steward-2","dest":"QhPth6AVhCDTbRtYTnKbPa","role":"2","verkey":"Dv6Kruwhm2Tgnga3x1KaBfUVePdrsSQEZUvGptK26nvs"},"metadata":{"from":"FKCQJg2EMprKRvXx7dxGPn"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-1","dest":"UUFZCbBj6XYkqpEKC25haa","role":"2","verkey":"FyNobukEM3vitxeR7hHeirfL9nTusV2qLkJrV4szWkte"},"metadata":{"from":"FKCQJg2EMprKRvXx7dxGPn"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"partner-steward-2","dest":"wQhf4EyqXWPopq36symdt","role":"2","verkey":"Wexvs9dZiTmCq12FSAujx6dZXgccvfsNLh4kfSpS6YR"},"metadata":{"from":"FKCQJg2EMprKRvXx7dxGPn"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
